name: test

on:
  push:
    branches:
      - develop

jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: create-release-pr
        uses: grassedge/git-pr-release-action@v1.0
        with:
          base: master
          head: develop
          token: ${{ secrets.PR_TOKEN }}
          labels: a,b,c
          assign: true